//
//  Strings.swift
//  Birthday Reminder
//
//  Created by Zeinab Khosravinia on 5/4/1400 AP.
//

import UIKit

struct Strings {
    static let home = "خانه"
    static let add = "ثبت تولد جدید"
    static let settings = "تنظیمات"
    static let noBirthday = "امروز تولد هیچ کس نیست :)"
    static let todayBirthdays = "امروز"
    static let todayBirthdaysComment = "امروز تولد کیا رو باید تبریک بگم؟"
    static let birthdayList = "لیست تولدهای ثبت شده"
    static let birthdayListComment = "تولد کیا تو راهه؟"
    static let noRegisteredBirthday = "هنوز هیچ تولدی ثبت نشده!"
    static let remaningDay = "روز مانده"
    static let name = "نام"
    static let birthday = "تاریخ تولد"
    static let gender = "جنسیت"
    static let profileImage = "تصویر پروفایل"
    static let male = "آقا"
    static let female = "خانم"
    static let changeImage = "تغییر تصویر"
    static let clearForm = "پاک سازی فرم"
    static let save = "ذخیره"
    static let remove = "حذف تولد"
    static let enterName = "لطفا نام را وارد نمایید."
    static let enterBirthday = "لطفا تاریخ تولد را وارد نمایید."
    static let selectGender = "لطفا جنسیت را انتخاب کنید."
    static let close = "بستن"
    static let error = "خطا"
    static let cancel = "انصراف"
    static let removeCurrentImage = "حذف تصویر"
    static let selectFromGallery = "انتخاب از گالری"
    static let takePicture = "گرفتن عکس با دوربین"
    static let successAlert = "تولد با موفقیت ثبت شد!"
    static let ok = "تایید"
    static let areYouSure = "آیا از حذف این تولد اطمینان دارید؟"
    static let todayIsSomeoneBirthday = "امروز تولد %@ هست!"
    static let sayCongrate = "بهش تبریک بگم"
    static let defaultCongrateMessage = "🌸🌸🌸دوستان امروز تولد %@ رو داریم، تولدتون مبارک باشه و امیدوارم همیشه شاد و موفق باشید🌸🌸🌸"
    static let notificationMessage = "امروز تولد %@ هست، یادت نره تبریک بگی 😉"
    static let version = "نسخه %@"
    static let notifTime = "ساعت یادآوری"
    static let defaultMessage = "متن تبریک پیش فرض"
    static let defaultMessagePart1 = "بخش اول متن تبریک (پیش از نام)"
    static let defaultMessagePart2 = "بخش دوم متن تبریک (پس از نام)"
    static let settingSaved = "تنظیمات مورد نظر با موفقیت تغییر کرد"
    static let importTitle = "بازیابی لیست تولدها"
    static let exportTitle = "به اشتراک گذاری لیست تولدها"
    static let addFromListAlertMessage = "تعداد %d آیتم بازیابی شد."
    static let invalidCSVFormat = "فرمت فایل انتخاب شده نادرست می باشد"
    static let addToCurrentList = "افزودن آیتم ها به لیست جاری"
    static let replaceWithCurrentList = "جایگذاری آیتم ها با لیست جاری"
    static let successImportAlert = "عملیات بازیابی با موفقیت انجام شد."
}
